<font size = 6> <b> Numpy! </b> </font>

In [1]:
import numpy as np
from numpy import random

<font size = 5> <b> Creating Numpy Arrays </b> </font> <br>
<font size = 3> <b> Method 1: Numpy Array from Python List </b></font>

In [2]:
list1=[1,2,3,4,5]
npArr1 = np.array(list1, dtype=np.int16) #type specification is optional
print("npArr1: \n", npArr1)
list2=[[1,2,3],[4,5,6],[7,8,9]]
npArr2=np.array(list2)
print("npArr2: \n", npArr2)

npArr1: 
 [1 2 3 4 5]
npArr2: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


<font size = 3><b> Method 2: Using arange and linspace </b> </font> <br><br>
The arange(start, stop, step) constructs a np array from the starting position (inclusive) to the ending position (exclusive) in increments defined by the step size. Default step size = 1. Compared to linspace, arange gives the user more control over the step size. <br><br>
The linspace(start, stop, array length) constructs a np array from the starting position (inclusive) to the ending position (inclusive) with equally spaced value. The returned array will have the specified number of elements. Compared to arange, linspace gives the user more control over the start and stop values.

In [3]:
print("arange:", np.arange(1,10, 2))
print("linspace:", np.linspace(0,10,4))

arange: [1 3 5 7 9]
linspace: [ 0.          3.33333333  6.66666667 10.        ]


<font size = 3><b> Method 3: Using ones and zeros </b> </font>

In [10]:
print(np.zeros(2))
print(np.zeros((2,2)))
print(np.ones((3,4)).size)
print(np.ones((3,4)).shape)
print(np.ones((3,4)).dtype)

[0. 0.]
[[0. 0.]
 [0. 0.]]
12
(3, 4)
float64


<font size = 3><b> Method 4: Creating random arrays</b> </font><br><br>
The np.random.randint(from, to, size) function generates an array of size n with integers values ranging from (inclusive) and to (exclusive) the first two arguments. Default from = 0, size = 1.<br><br>

In [13]:
print(np.random.randint(10,21,10)) #from (inclusive), to (exclusive), n
print(np.random.randint(10,21, size=(2,2)))

[16 11 12 18 17 18 11 16 12 19]
[[12 19]
 [16 18]]


The np.random.rand(n) function creates an array of size n with random values from a uniform distribution from 0 to 1. Default n=1.

In [22]:
print(np.random.rand())
print(np.random.rand(2,2))

0.21168162997807338
[[0.02848798 0.7492517 ]
 [0.60277253 0.52815832]]
