<font size = 6> <b> Numpy! </b> </font>

In [1]:
import numpy as np
from numpy import random

<font size = 5> <b> Creating Numpy Arrays </b> </font> <br>
<font size = 3> <b> Method 1: Numpy Array from Python List </b></font>

In [2]:
list1=[1,2,3,4,5]
npArr1 = np.array(list1, dtype=np.int16) #type specification is optional
print("npArr1: \n", npArr1)
list2=[[1,2,3],[4,5,6],[7,8,9]]
npArr2=np.array(list2)
print("npArr2: \n", npArr2)

npArr1: 
 [1 2 3 4 5]
npArr2: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


<font size = 3><b> Method 2: Using arange and linspace </b> </font> <br><br>
The arange(start, stop, step) constructs a np array from the starting position (inclusive) to the ending position (exclusive) in increments defined by the step size. Default step size = 1. Compared to linspace, arange gives the user more control over the step size. <br><br>
The linspace(start, stop, array length) constructs a np array from the starting position (inclusive) to the ending position (inclusive) with equally spaced value. The returned array will have the specified number of elements. Compared to arange, linspace gives the user more control over the start and stop values.

In [3]:
print("arange:", np.arange(1,10, 2))
print("linspace:", np.linspace(0,10,4))

arange: [1 3 5 7 9]
linspace: [ 0.          3.33333333  6.66666667 10.        ]


<font size = 3><b> Method 3: Using ones and zeros </b> </font>

In [4]:
print(np.zeros(2))
print(np.zeros((2,2)))
print(np.ones((3,4)).size)
print(np.ones((3,4)).shape)
print(np.ones((3,4)).dtype)

[0. 0.]
[[0. 0.]
 [0. 0.]]
12
(3, 4)
float64


<font size = 3><b> Method 4: Creating random arrays</b> </font><br><br>
The np.random.randint(from, to, size) function generates an array of size n with integers values ranging from (inclusive) and to (exclusive) the first two arguments. Default from = 0, size = 1.<br><br>

In [5]:
print(np.random.randint(10,21,10)) #from (inclusive), to (exclusive), n
print(np.random.randint(10,21, size=(2,2)))

[12 15 14 14 16 19 11 17 18 15]
[[13 11]
 [10 16]]


The np.random.rand(n) function creates an array of size n with random values from a uniform distribution from 0 to 1. Default n=1.

In [6]:
print(np.random.rand())
print(np.random.rand(2,2))

0.672770046677414
[[0.62618377 0.72973687]
 [0.61103718 0.13547415]]


The np.random.choice(a, size=None, replace=True, p=None) function randomly chooses elements from a given input a.

In [7]:
input = [1,2,3,4,5]
print(np.random.choice(input, size=(2,2), replace=True, p=[0.1,0.1,0.1,0.1,0.6]))

[[2 5]
 [3 2]]


In [8]:
arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[2 4 3 5 1]


The np.random.permutation(arr) function returns a permutation of the elements in the input array. Unlike the shuffle function, the permutation function does not affect the original array.

In [9]:
arr=np.array([1,2,3,4,5])
print(np.random.permutation(arr))

[4 2 3 1 5]


The np.random.normal(loc=0, scale=1, size=None) returns random values from a normal distruction with mean=loc and standard deviation = 1.

In [10]:
print(np.random.normal(2,0.1, size=(3,3)))

[[1.84484052 1.98118519 2.11342608]
 [1.82833679 2.09128662 2.04067067]
 [1.91606073 1.86303647 2.06999231]]


<font size = 5> <b> Slicing and Indexing </b> </font> <br>

There are two ways to access an item in a numpy array. We can use standard indexing, or we can use the np.item function. Note that indexing will allow us to extract a row or column, but the np.item function will only allow us to access a single item, not a row.

In [11]:
arr=np.array([[1,2],[3,4]])
print(arr[0,0])
print(arr[0])
print(arr.item(0,1))

1
[1 2]
2


There are two ways to set an item in a numpy array. We can use standard assignment with the '=' operator, or we can use the np.itemset function.

In [12]:
arr=np.zeros((3,3), dtype=int)
arr[0,0] = 1
arr.itemset(0,1,1) #(row, col, val)
print(arr)

[[1 1 0]
 [0 0 0]
 [0 0 0]]


The np.take function allows us to extract multiple items at once. The array is "flattened", and each element is indexed with a single value.

In [13]:
arr=np.array([[1,2],[3,4]])
arr.take([1,2])

array([2, 3])

The np.put function allows us to set multiple items at once. The array is "flattened", and we provide first the indicies of the elements to change, and then the values to change them to.

In [15]:
arr=np.zeros((3,3))
arr.put([1,5,8], [10,10,10])
print(arr)

[[ 0. 10.  0.]
 [ 0.  0. 10.]
 [ 0.  0. 10.]]


We can observe the .shape and .size attributes of an array.

In [16]:
print(arr.size)
print(arr.shape)

9
(3, 3)


We can slice a numpy array with the \[from:to:by\] syntax. Note that this _includes_ the starting point and _excludes_ the ending point. The default is \[beginning:end:1\].

In [17]:
arr2=np.array([1,2,3,4,5,6,7,8,9,0])
print("arr2: ", arr2)
print(arr2[:5:2])

arr2:  [1 2 3 4 5 6 7 8 9 0]
[1 3 5]


We can slice a multidimension array as follows. If only one list-like object is present, such as in arr\[1:3]\ then the slicing applies to rows (the outermost dimension) only. If we wish to select specific columns and all rows, then we must specify that, such as with the syntax arr\[:, 1:3\] where the first ":" indicates that we will use all rows, and the "1:3" indicates that we will use the second and third columns.

In [24]:
arr3=np.array([[1,2,3], [4,5,6], [7,8,9]])
print("arr3\n",arr3)
print("arr3[:, 0:2]\n", arr3[:, 0:2]) #all rows, only cols 0 and 1
print("arr3[::-1]\n", arr3[::-1]) #reverses the order of the rows, not the columns
print("arr3[::-1, ::-1]\n", arr3[::-1, ::-1]) #reverses both

arr3
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr3[:, 0:2]
 [[1 2]
 [4 5]
 [7 8]]
arr3[::-1]
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
arr3[::-1, ::-1]
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


We can also index an array by passing a boolean array. This returns a _flattened_ array with values from the original array that correspond to True elements in the indexing array.

In [25]:
print("Evens only")
evens=arr3[arr3%2 == 0]
print(evens)

Evens only
[2 4 6 8]


We can filter out the unique elements of an array with the .unique() function.

In [26]:
np.unique(arr3)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

We can reshape or resize arrays with the .reshape and .resize functions. The .reshape() function returns a reshaped array but does not modify the original values, whereas the .resize() function does modify the original values. The array is flattened, and values are filled into the new shape in the order of the flattened array. Note that with the reshape function, we must pass a new shape that maintains the original size of the array. However, with the resize function, we can truncate the array by passing a new size that is smaller than the original array.

In [38]:
arr3=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr3.reshape((3,3))) #returns reshaped array but does not modify original values
print(arr3)
arr3.resize(1,8)
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8]]


We can swap axes with the .swapaxes() function. For 2D arrays, this is equivalent to taking the transpose of the matrix.

In [39]:
arr3.swapaxes(0,1)
print(arr3)

[[1 2 3 4 5 6 7 8]]


We can flatten a multidimensional array with the .flatten() function. By default, we flatten rows first, so the output 1D array contains the first row, then the second row, and so on until the last row. We can also flatten by columns by passing 'F' to the flatten function. Note that this function does not modify the original array.

In [44]:
arr3=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr3.flatten())
print(arr3.flatten("F"))

[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
