<font size=6> <b> Pytorch! </b> </font>

First we install pytorch and numpy.

In [2]:
import torch
import numpy as np

Tensors are like nparrays except that they can be used on the GPU (or other hardware) to accelerate computation. Tensors all contain the same datatype. <br>

If cuda is available, we can use cuda to transfer tensors to and from the GPU.

In [4]:
print(torch.cuda.is_available())

True


We can create tensors from nparrays as follows.

In [5]:
arr=np.arange(10)
tensor=torch.from_numpy(arr)
print(tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


We can also create tensors from lists.

In [8]:
tensor2=torch.tensor(([1,2,3],[4,5,6]))
print(tensor2)

tensor([[1, 2, 3],
        [4, 5, 6]])


We can create a tensor filled with zeros, ones, or random values for any given shape.

In [18]:
print(torch.ones(3,4))
print(torch.zeros(2,3))
print(torch.rand(5))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0.8043, 0.5452, 0.7555, 0.4217, 0.8258])


We can create tensors to have the same shape and size as another tensor, and fill it with ones, zeros, or random values as follows. Note that for rand_like, we must set the datatype to float since the datatype of tensor2 is int32, so we must override this datatype.

In [14]:
tensor3=torch.ones_like(tensor2)
print(tensor3)
tensor4=torch.zeros_like(tensor2)
print(tensor4)
tensor5=torch.rand_like(tensor2, dtype=torch.float)
print(tensor5)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0.8382, 0.1522, 0.8041],
        [0.6957, 0.6409, 0.0391]])


We can access the values in a tensor like we do for a nparray as follows.

In [22]:
t=torch.tensor([3,4,5,6])
print(t[0])
print(t[1:3])
t2=torch.tensor([[1,2,3],[4,5,6]])
print(t2[0])
print(t2[:,0])

tensor(3)
tensor([4, 5])
tensor([1, 2, 3])
tensor([1, 4])


Likewise, we can set values for a tensor as follows.

In [29]:
t=torch.ones(4,4)
t[:,0]=0
print(t)
t=torch.tensor([1,2,3])
t[0]=10
print(t)

tensor([[0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.]])
tensor([10,  2,  3])


We can join tensors together along a given dimension with the torch.cat operation.

In [34]:
t1=torch.tensor([[1,2],[3,4]])
t2=torch.tensor([[10,20],[30,40]])
print(torch.cat([t1, t2], dim=0)) #add vertically, maintain each row
print(torch.cat([t1, t2], dim=1)) #add horizontally, maintain each column

tensor([[ 1,  2],
        [ 3,  4],
        [10, 20],
        [30, 40]])
tensor([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40]])


We can perform matrix multiplication using the @ symbol, and take the transform of a matrix using the .T function. Alternatively, we can use the torch.matmul() function

In [41]:
print(t1 @ t1.T)
print(t1.matmul(t1.T))
print(torch.matmul(t1, t1.T))
torch.matmul(t1,t1.T, out=t2) #"out" must be pre-defined
print(t2)

tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])


We can compute the element-wise product using the * symbol or the .mul function.

In [43]:
print(t1 * t1)
print(t1.mul(t1))
torch.mul(t1, t1, out=t2)
print(t2)

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


A 1-element tensor can be converted to a python value using the item() function.

In [46]:
agg = t1.sum()
print(agg)
agg_val = agg.item()
print(agg_val)

tensor(10)
10


"In place" operations, denoted with an underscore, store the result into the operand. These functions can be problematic when computing derivatives because data is immediately overwritten, so the use of in place operations is discouraged.

In [48]:
print(t1)
t1.add_(5)
print(t1)

tensor([[1, 2],
        [3, 4]])
tensor([[6, 7],
        [8, 9]])


"Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other."

In [51]:
t = torch.ones(5)
n = t.numpy()
print("t: ", t)
print("n: ", n)
t.add_(5)
print("updated t: ", t)
print("updated n: ", n)

t:  tensor([1., 1., 1., 1., 1.])
n:  [1. 1. 1. 1. 1.]
updated t:  tensor([6., 6., 6., 6., 6.])
updated n:  [6. 6. 6. 6. 6.]


In [52]:
n=np.ones(5)
t=torch.from_numpy(n)
np.add(n, 1, out=n)
print(t)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
